[package]
name = "monb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brightness = "0.5.0"
logger = { path = "../logger", version = "0.1.0" }
